### PR TITLE
fix: near archive testnet

### PR DESCRIPTION
**Pull request by BabyScope**
Hi, 

the archive for testnet is started at 42376888.
https://testnet.neardata.xyz/
https://testnet.neardata.xyz/v0/first_block
https://testnet.neardata.xyz/v0/block/42376888

### CODE REVIEW

**Comment by Yaroms** [comment]
@BabyScope we changed the file name from spec_add_near.json -> near.json, can you please change it in the PR as well?

**Comment by BabyScope** [comment]
@Yaroms done!

**Comment by Yaroms** [comment]
@BabyScope also since the testnet inherits the mainnet you can actually just set the "values" field instead of setting the whole struct, just like the "chainid" verification above it

**Comment by BabyScope** [comment]
@Yaroms  changed it

**Review by omerlavanet — APPROVED** [review]

**Pull request merged**
