### PR TITLE
CNS-593: fix "make proto-gen" breakage

### PR DESCRIPTION
**Pull request by orenl-lava**
The build 'make proto-gen' stopped working because the 'proto-build' docker image from cosmos no longer supports bash. Fix by adjusting the script to be compatible with 'sh' instead of 'bash'.

### CODE REVIEW

**Comment by Yaroms** [comment]
using this branch, trying protogenc.sh on my env doesnt work:
./scripts/protocgen.sh
./scripts/protocgen.sh: 3: source: not found
./scripts/protocgen.sh: 5: command_exists: not found

**Comment by orenl-lava** [comment]
> using this branch, trying protogenc.sh on my env doesnt work:

sigh, that was incomplete commit. fixed.

**Comment by oren-lava** [comment]
Not a must, but when I'm running ./scripts/protocgen.sh from this branch, it prints "option" strings like this: `option go_package = "github.com/lavanet/lava/common/types";`
Can you make it not print that (like before)?

**Comment by orenl-lava** [comment]
Done.

**Review by Yaroms — APPROVED** [review]

**Pull request merged**
