### PR TITLE
feat: added ethermint to all legacy proposals

### PR DESCRIPTION
**Pull request by BabyScope**
Added ethermint to all legacy proposals where needed.

### CODE REVIEW

**Comment by omerlavanet** [comment]
@BabyScope it seems like it's failing the tests, if you run the commands manually what does it fail with?

**Comment by BabyScope** [comment]
@omerlavanet  i don't understand why it is failing because when i tried to run a test for Lava i couldn't pas the legacy propsals 
with error;
invalid spec ErrMsg: spec expand failed ErrMsg: imported spec unknown: ETHERMINT {imports:EVMOS->[COSMOSSDK,ETHERMINT(unknown)}: imported spec unknown: ETHERMINT {imports:COSMOSSDK,ETHERMINT,ETH1}: spec expand failed ErrMsg: imported spec unknown: ETHERMINT {imports:EVMOS->[COSMOSSDK,ETHERMINT(unknown)}: imported spec unknown: ETHERMINT: invalid proposal content: invalid proposal content [cosmos/cosmos-sdk@v0.47.10/x/gov/keeper/proposal.go:74] With gas wanted: '18446744073709551615' and gas used: '4324938' : unknown request

Next error is :

invalid spec ErrMsg: spec expand failed ErrMsg: imported spec unknown: COSMOSSDKFULL {imports:LAV1->[COSMOSSDKFULL(unknown)}: imported spec unknown: COSMOSSDKFULL {imports:COSMOSSDKFULL}: spec expand failed ErrMsg: imported spec unknown: COSMOSSDKFULL {imports:LAV1->[COSMOSSDKFULL(unknown)}: imported spec unknown: COSMOSSDKFULL: invalid proposal content: invalid proposal content [cosmos/cosmos-sdk@v0.47.10/x/gov/keeper/proposal.go:74] With gas wanted: '18446744073709551615' and gas used: '395994' : unknown request


When i run the test with added Ethermint added there ;
[+] letting providers start and running health check then running command with flags:  http://127.0.0.1:3001 LAV1 rest
Jun  5 13:07:39 INF RPCConsumer Test started args=http://127.0.0.1:3001;LAV1;rest
Jun  5 13:07:39 INF setting log level loglevel=info
Jun  5 13:07:39 INF lavad Binary Version: 
Jun  5 13:07:47 INF Received a new Block Chain=LAV1 apiInterface=rest block=1343859 hash=CGou4aZKOLTadmMITMMQYVY1lUwauD2h29nQPN0nhz4=
Jun  5 13:08:03 INF Received a new Block Chain=LAV1 apiInterface=rest block=1343860 hash=1UHWnsqI68V55xRqDWfXknuEdEix1n+4fRmOC/sG3XM=
Jun  5 13:08:20 INF Received a new Block Chain=LAV1 apiInterface=rest block=1343861 hash=4FilXrv9pwFBMixlvjh+HTyv4OFRH0afpveE/7SjdWg=
Jun  5 13:08:36 INF Received a new Block Chain=LAV1 apiInterface=rest block=1343862 hash=qYFKbW0aeSr/0HFUFnMV9SEk/wXQF4Y+qg89PDnO0L0=
It is running fine no problems

**Comment by omerlavanet** [comment]
looks like an inheritance order, for some reason the cosmossdkfull isn't accepted with the ethermint change (probably expand order), specs need to be added in the same order of inheritance

**Comment by omerlavanet** [comment]
already merged in another PR, well done catching this @BabyScope

**Pull request closed without merging**
