### PR TITLE
feat: dymension spec add

### PR DESCRIPTION
**Pull request by BabyScope**
[DYMENSION LOG.txt](https://github.com/lavanet/lava/files/15220389/DYMENSION.LOG.txt)
[DYMENSION PORTAL.txt](https://github.com/lavanet/lava/files/15220390/DYMENSION.PORTAL.txt)

I added ethermint api in Dymension cause evmos not using. Evmos is using ethermint in there grpc so the ones that are not in Evmos i added also in the grpc.

### CODE REVIEW

**Comment by Yaroms** [comment]
@omerlavanet i think the best way is to create a spec specific for ethermint

**Comment by omerlavanet** [comment]
yes would make a lot of sense, create ethermint base spec and inherit form it, @BabyScope want to give it a go?

**Comment by BabyScope** [comment]
I will try it out

**Comment by BabyScope** [comment]
Changed the spec of dymension added Ethermint to imports. Also changed the test script ethermint is added to the legacy proposal.

**Comment by Yaroms** [comment]
@BabyScope for the tests to pass we need to set the ethermint spec as base spec in the following test:
https://github.com/lavanet/lava/blob/4daa8f49185d71a46efa28bbbf319bdecef1596c/x/spec/keeper/spec_test.go#L811

**Comment by BabyScope** [comment]
@Yaroms i added it to the spec_test but he is still failling? do i something wrong here?

**Pull request closed without merging**
